// examples/eden-svelte-query-basic/src/routes/+page.svelte
<script lang="ts">
  import { eden } from '$lib/eden'

  const hello = eden.api.index.get.createQuery({})
</script>

<main>
  <h1>Home</h1>

  <div>
    {#if $hello.isLoading}
      <p>loading...</p>
    {:else if $hello.isError}
      <p>Error: {$hello.error.message}</p>
    {:else}
      <p>
        <b>Data: </b>
        <span>{$hello.data}</span>
      </p>
    {/if}
  </div>
</main>

// examples/eden-react-query-basic/src/routes/+page.tsx
import { eden } from '../lib/eden'

export default function Page() {
  const hello = eden.api.index.get.useQuery({})

  return (
    <main>
      <h1>Home</h1>

      <div>
        {hello.isLoading ? (
          <p>Loading...</p>
        ) : hello.isError ? (
          <p>Error: {hello.error.message}</p>
        ) : (
          <p>
            <b>Data: </b>
            <span>{hello.data}</span>
          </p>
        )}
      </div>
    </main>
  )
}
