// examples/svelte-treaty/src/routes/+page.svelte
<script lang="ts">
  import { eden } from '$lib/eden'

  const index = eden.api.index.get.createQuery({})
  const count = eden.api.count.get.createQuery({})
</script>

<div>
  <h1>Home</h1>
  <pre>{JSON.stringify($index.data, null, 2)}</pre>
  <pre>{JSON.stringify($count.data, null, 2)}</pre>
</div>

// examples/eden-react-query-basic/src/routes/+page.tsx
import { eden } from '../lib/eden'

export default function Page() {
  const hello = eden.api.index.get.useQuery({})

  return (
    <main>
      <h1>Home</h1>

      <div>
        {hello.isLoading ? (
          <p>Loading...</p>
        ) : hello.isError ? (
          <p>Error: {hello.error.message}</p>
        ) : (
          <p>
            <b>Data: </b>
            <span>{hello.data}</span>
          </p>
        )}
      </div>
    </main>
  )
}
