// examples/eden-react-query-basic/src/routes/batch/+page.tsx
import { eden } from '../../lib/eden'

export default function Page() {
  const hello = eden.api.index.get.useQuery()

  const bye = eden.api.bye.get.useQuery()

  return (
    <main>
      <h1>Batch</h1>

      <p>
        Because two queries are launched concurrently, the request is actually made to a /batch
        endpoint.
      </p>

      <div>
        {hello.isLoading ? (
          <p>Hello loading...</p>
        ) : hello.isError ? (
          <p>
            <b>Hello Error: </b>
            <span>{hello.error.message}</span>
          </p>
        ) : (
          <p>
            <b>Hello Query: </b>
            <span>{hello.data}</span>
          </p>
        )}
      </div>

      <hr />

      <div>
        {bye.isLoading ? (
          <p>Bye loading...</p>
        ) : bye.isError ? (
          <p>
            <b>Bye Error: </b>
            <span>{bye.error.message}</span>
          </p>
        ) : (
          <p>
            <b>Bye Query: </b>
            <span>{bye.data}</span>
          </p>
        )}
      </div>
    </main>
  )
}

// examples/eden-svelte-query-basic/src/routes/batch/+page.svelte
<script lang="ts">
  import { eden } from '$lib/eden'

  const hello = eden.api.index.get.createQuery({})

  const bye = eden.api.bye.get.createQuery({})
</script>

<main>
  <h1>Batch</h1>

  <p>
    Because two queries are launched concurrently, the request is actually made to a /batch
    endpoint.
  </p>

  <div>
    {#if $hello.isLoading}
      <p>Hello loading...</p>
    {:else if $hello.isError}
      <p>
        <b>Hello Error: </b>
        <span>{$hello.error.message}</span>
      </p>
    {:else}
      <p>
        <b>Hello Query: </b>
        <span>{$hello.data}</span>
      </p>
    {/if}
  </div>

  <hr />

  <div>
    {#if $bye.isLoading}
      <p>Bye loading...</p>
    {:else if $bye.isError}
      <p>
        <b>Bye Error: </b>
        <span>{$bye.error.message}</span>
      </p>
    {:else}
      <p>
        <b>Bye Query: </b>
        <span>{$bye.data}</span>
      </p>
    {/if}
  </div>
</main>
