// examples/eden-react-query-basic/src/routes/index.tsx
import { eden } from '../lib/eden'

export default function Page() {
  const hello = eden.api.index.get.useQuery({}, { eden: {} })

  const bye = eden.api.bye.get.useQuery({})

  return (
    <main>
      <h1>Hello, World!</h1>

      <div>
        <p>Hello: </p>

        {hello.isLoading ? (
          <p>Loading...</p>
        ) : hello.isError ? (
          <p>Error: {hello.error.message}</p>
        ) : (
          <p>Result: {hello.data}</p>
        )}
      </div>

      <hr />

      <div>
        <p>Bye: </p>
        {bye.isLoading ? (
          <p>Loading...</p>
        ) : bye.isError ? (
          <p>Error: {bye.error.message}</p>
        ) : (
          <p>Result: {bye.data}</p>
        )}
      </div>
    </main>
  )
}

// examples/eden-svelte-query-basic/src/routes/+page.svelte
<script lang="ts">
  import { eden } from '$lib/eden'

  const hello = eden.api.index.get.createQuery({})
</script>

<main>

  {#if $hello.isLoading}
    <h1>loading...</h1>
  {:else if $hello.isError}
    <h1>Error: {$hello.error.message}</h1>
  {:else}
    <h1>
      {$hello.data}
    </h1>
  {/if}
</main>
