// examples/eden-svelte-query-basic/src/routes/mutation/+page.svelte
<script lang="ts">
  import { eden } from '$lib/eden'

  const todos = eden.api.todos.get.createQuery()

  const addTodo = eden.api.todos.post.createMutation()

  const deleteTodo = eden.api.todos.delete.createMutation()

  const utils = eden.getContext()

  let content = ''

  async function handleAddTodo() {
    await $addTodo.mutateAsync({ completed: false, content })
    await utils.api.todos.get.invalidate()
    content = ''
  }

  async function handleDeleteTodo(id: string) {
    await $deleteTodo.mutateAsync(id)
    await utils.api.todos.get.invalidate()
  }
</script>

<main>
  <h1>Mutation</h1>

  <p>Todos:</p>

  <ul>
    {#each $todos.data ?? [] as todo}
      <li style="display: flex; align-items: center; gap: 1rem">
        <input type="checkbox" checked={todo.completed} />
        <p>{todo.content}</p>
        <button on:click|preventDefault={async () => await handleDeleteTodo(todo.id)}>
          Delete
        </button>
      </li>
    {/each}
  </ul>

  <form on:submit={handleAddTodo}>
    <input type="text" bind:value={content} />
    <button>Add Todo</button>
  </form>
</main>

// examples/eden-react-query-basic/src/routes/mutation/+page.tsx
import { useState } from 'react'

import { eden } from '../../lib/eden'

export default function Page() {
  const todos = eden.api.todos.get.useQuery()

  const addTodo = eden.api.todos.post.useMutation()

  const deleteTodo = eden.api.todos.delete.useMutation()

  const utils = eden.useUtils()

  const [content, setContent] = useState('')

  const handleAddTodo = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    await addTodo.mutateAsync({ completed: false, content })
    await utils.api.todos.get.invalidate()
    setContent('')
  }

  const handleDeleteTodo = async (id: string) => {
    await deleteTodo.mutateAsync(id)
    await utils.api.todos.get.invalidate()
  }

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setContent(event.target.value)
  }

  return (
    <main>
      <h1>Mutation</h1>

      <p>Todos:</p>

      <ul>
        {todos.data?.map((todo) => {
          return (
            <li key={todo.id} style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <input type="checkbox" defaultChecked={todo.completed} />
              <p>{todo.content}</p>
              <button onClick={async () => await handleDeleteTodo(todo.id)}>Delete</button>
            </li>
          )
        })}
      </ul>

      <form onSubmit={handleAddTodo}>
        <input type="text" value={content} onChange={handleInputChange} />
        <button>Add Todo</button>
      </form>
    </main>
  )
}
