// examples/eden-react-query-basic/src/routes/abort/+page.tsx
import { useState } from 'react'

import { eden } from '../../lib/eden'

export default function Page() {
  const [show, setShow] = useState(false)

  const toggle = () => {
    setShow((previous) => !previous)
  }

  return (
    <main>
      <h1>Abort</h1>

      <button onClick={toggle}>Toggle Component</button>

      <p>
        The toggle-able component does a long query. If it's hidden before the request ends, then
        the request should be aborted.
      </p>

      {show && <Sleep />}
    </main>
  )
}

function Sleep() {
  const sleep = eden.api.sleep.get.useQuery()

  return (
    <div>
      <p>
        <span>Result: </span>
        {sleep.isLoading ? <span>Loading...</span> : <span>{sleep.data}</span>}
      </p>
    </div>
  )
}

// examples/eden-svelte-query-basic/src/routes/abort/+page.svelte
<script lang="ts">
  import Sleep from '$lib/sleep.svelte'

  export let show = false

  function toggle() {
    show = !show
  }
</script>

<main>
  <h1>Abort</h1>

  <button on:click|preventDefault={toggle}>Toggle Component</button>

  <p>
    The toggle-able component does a long query. If it's hidden before the request ends, then the
    request should be aborted.
  </p>

  {#if show}
    <Sleep />
  {/if}
</main>
